#!/bin/bash

USER=$1

if [ $# -lt 1 ]; then
    echo "ERROR please provide a <userid>"
    exit 1
fi

grep -q 'start-services.js' /etc/rc.local
services=$?
grep -q $USER /etc/rc.local
user=$?
if [ $services -eq 0 ]; then
    if [ $user -eq 0 ]; then
	echo "Adding qed services to $USER"
	echo "(sudo -u $USER bash -c "cd /home/$USER/qed && ./start-services.js")&" >> /etc/rc.local
    else
	echo "Found qed services for $USER"
    fi
fi
